services:
  # Development service
  businessapp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  # Production service
  businessapp-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 