name: Development Build Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for linting errors
      run: npm run lint --if-present
      
    - name: Build application
      run: npm run build
      
    - name: Test Docker build
      run: |
        docker build -t business-calculator-test .
        docker run --rm business-calculator-test echo "Docker build successful"
        
    - name: Success message
      run: |
        echo "✅ Build test passed!"
        echo "🚀 Ready for deployment" 